### ISSUE TITLE
Error in verification

### ISSUE THREAD

**Issue by ricky5151** [HealthCatalyst/healthcareai-py#464]
It happens that when I am trying to import SupervisedModelTrainer from healthcareai, the error shown out as below. Is there any method to solve this problem?

`Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from healthcareai import SupervisedModelTrainer
  File "/usr/local/lib/python3.4/dist-packages/healthcareai/__init__.py", line 1, in <module>
    from .advanced_supvervised_model_trainer import AdvancedSupervisedModelTrainer
  File "/usr/local/lib/python3.4/dist-packages/healthcareai/advanced_supvervised_model_trainer.py", line 9, in <module>
    import healthcareai.common.model_eval as hcai_model_evaluation
  File "/usr/local/lib/python3.4/dist-packages/healthcareai/common/model_eval.py", line 142
    return {'accuracy': accuracy, **roc, **pr}
                                   ^
SyntaxError: invalid syntax
`

**Comment by mxlei01** [comment]
@ricky5151 

What version of python are you using?

**Comment by ricky5151** [comment]
3.4.2

Best Regards,
Ooi Yoong Khang
